# Generated by Django 5.0.3 on 2024-04-05 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('courses', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('tution_desc', models.CharField(max_length=200)),
                ('tution_location', models.CharField(max_length=100)),
                ('preferred_timing', models.CharField(max_length=100)),
                ('preferred_tutor', models.CharField(max_length=200)),
                ('fee_offered', models.CharField(max_length=100)),
                ('tution_type', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('posted_on', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(max_length=100)),
                ('hourly_price', models.CharField(max_length=100)),
                ('preferred_timing', models.CharField(max_length=100)),
                ('about_me', models.CharField(max_length=200)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
